### ISSUE TITLE
Build from master, then run local server is hanging

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1264]
Steps:

- Checkout from master
- npm install
- npm start
- Accessing http://0.0.0.0:8088/ in a browser hangs

**Comment by ldimaggi** [comment]
The problem seems to have been introduced sometime after this PR:
https://github.com/fabric8io/fabric8-planner/pull/1243

**Comment by naina-verma** [comment]
![screenshot from 2017-03-23 19-33-32](https://cloud.githubusercontent.com/assets/19172870/24251284/a5bdbfee-0fff-11e7-9462-5bbc978a1a74.png)

**Comment by michaelkleinhenz** [comment]
This is due to a PR that we merged a bit too early. This requires an update on ngx-widgets. Joshua is working on that PR. The only question is, why did the PR check on https://github.com/fabric8io/fabric8-planner/pull/1240 did turn green. @ldimaggi @naina-verma can you take a look at that one? I think there is something off with the tests..

**Comment by ldimaggi** [comment]
Unit tests:

webpack: Compiled successfully.
23 03 2017 10:55:10.641:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
23 03 2017 10:55:10.643:INFO [launcher]: Launching browser PhantomJS_custom with unlimited concurrency
23 03 2017 10:55:10.650:INFO [launcher]: Starting browser PhantomJS
23 03 2017 10:55:10.704:INFO [phantomjs.launcher]: ACTION REQUIRED:
23 03 2017 10:55:10.704:INFO [phantomjs.launcher]: 
23 03 2017 10:55:10.704:INFO [phantomjs.launcher]:   Launch browser at
23 03 2017 10:55:10.704:INFO [phantomjs.launcher]:   http://localhost:9000/webkit/inspector/inspector.html?page=2
23 03 2017 10:55:10.704:INFO [phantomjs.launcher]: 
23 03 2017 10:55:10.704:INFO [phantomjs.launcher]: Waiting 15 seconds ...
23 03 2017 10:55:26.016:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket PMzDZpMOaPvmYympAAAA with id 3697319
  Iteration service - 
    ✔ Get iterations
    ✔ Get iteration with error
    ✔ Create iteration
    ✔ Create iteration with error
    ✔ Should check valid URL for iterations
    ✔ Update iteration
    ✔ Update iteration with API error
  Comment section for the work item detailed view - 
    ✔ Should have a parent comment element
    ✔ Should have an input to create comments
  Detailed view and edit a selected work item - 
    ✔ Page should display work item ID when logged in
    ✔ Page should display work item ID when not logged in
    ✔ Work item ID cannot be edited (change model) 
    ✔ Work item ID cannot be edited (change html) 
    ✔ Page should display page title when logged in
    ✔ Page should display page title when not logged in
    ✔ Edit icon displayed when logged in
    ✔ Edit icon to be undefined when not logged in
    ✔ Page should display non-editable work item title when not logged in
    ✔ Page should display clickable work item title when looged in
    ✔ Page should display editable work item title when logged in
    ✔ Work item title can be edited when logged in
    ✔ Save should be enabled if a valid work item title has been entered
    ✔ Save should be disabled if the work item title is blank
    ✔ Work item description can be edited when logged in
    ✔ Work item description cannot be edited when logged out
    ✔ Work item state can be edited when logged in
    ✔ should not open the user list if not logged in
    ✔ should open the user list if logged in
    ✔ Page should display correct assignee
    ✔ page should display correct reporter
    ✔ Should have a comment section
  Quick add work item component - 
    ✔ Should keep the Add button disabled if title contain only white spaces
    ✔ Should keep the Add button disabled if title contain empty string
    ✔ Should raise an error on save if the title contain only white space
  Work Item Service - 
    ✔ Get work items
    ✔ Add new work Item
    ✔ Delete work item
    ✔ Update work item

=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================

Finished in 9.481 secs / 9.546 secs @ 10:55:36 GMT-0400 (EDT)

SUMMARY:
✔ 38 tests completed
Unit tests OK

**Comment by ldimaggi** [comment]
Functional tests:

sh ./run_functional_tests.sh 
Using logfile /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/functional_tests.log
Updating Webdriver and Selenium...[10:55:43] I/file_manager - creating folder /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/node_modules/webdriver-manager/selenium
[10:55:44] I/downloader - curl -o /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.28.zip https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
[10:55:44] I/downloader - curl -o /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.3.1.jar https://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.1.jar
[10:55:45] I/downloader - curl -o /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.15.0.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
[10:55:45] I/update - chromedriver: unzipping chromedriver_2.28.zip
[10:55:45] I/update - chromedriver: setting permissions to 0755 for /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.28
[10:55:49] I/update - geckodriver: unzipping geckodriver-v0.15.0.tar.gz
[10:55:51] I/update - geckodriver: setting permissions to 0755 for /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.15.0
Starting Webdriver and Selenium...done.
Starting Almighty development server...done.
Building source...done.
Running tests...
[10:56:24] I/launcher - Running 1 instances of WebDriver
[10:56:24] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
[10:56:40] E/launcher - Error while running testForAngular: asynchronous script timeout: result was not received in 11 seconds
  (Session info: chrome=57.0.2987.98)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 3.10.0-505.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.07 seconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'ldimaggi.boston.csb', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-505.el7.x86_64', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f), userDataDir=/tmp/.org.chromium.Chromium.J6ZmVa}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.98, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: b6a12b9cf486b8a03306f876ac6a308c
[10:56:40] E/launcher - Error: Error while running testForAngular: asynchronous script timeout: result was not received in 11 seconds
  (Session info: chrome=57.0.2987.98)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 3.10.0-505.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11.07 seconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'ldimaggi.boston.csb', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-505.el7.x86_64', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f), userDataDir=/tmp/.org.chromium.Chromium.J6ZmVa}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.98, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: b6a12b9cf486b8a03306f876ac6a308c
    at executeAsyncScript_.then (/home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/protractor/lib/browser.ts:944:27)
    at ManagedPromise.invokeCallback_ (/home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/ldimaggi/local/redhat_git/go_path/src/github.com/vikram/fabric8-planner/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[10:56:40] E/launcher - Process exited with error code 199
4444/tcp:             7129
8088/tcp:             7159
Functional tests FAIL

**Comment by ldimaggi** [comment]
grep -ir showDropSlot src/*

src/app/work-item/work-item-list/work-item-list.component.html:                [showDropSlot]="true">

**Comment by ldimaggi** [comment]
Removing this line^ does not resolve the problem.

**Comment by michaelkleinhenz** [comment]
Yeah, the library might have introduced more that this. The patch is now merged, so we should try again.

**Comment by michaelkleinhenz** [comment]
[test]

**Comment by ldimaggi** [comment]
Much better now...

99 specs, 1 failure
Finished in 592.143 seconds

The failing test can be considered separately - closing this issue.
