### ISSUE TITLE
Repair functional UI tests - all are failing on Centos CI and when run on Docker

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#857]
What I found is that the tests are failing when run through the cico script - I ran the tests manually (docker exec almighty-ui-builder ./run_functional_tests.sh) and saw the same failures.

Many 
![6a3c424fda3585654e8985cda73c6e0e](https://cloud.githubusercontent.com/assets/642621/22481384/075ca2b6-e7c3-11e6-8746-488258f44b4c.png)
![b30c4aafc60593dd0039b7c9be2e2d28](https://cloud.githubusercontent.com/assets/642621/22481385/075cfd1a-e7c3-11e6-83f9-be67f86b2554.png)

hours later, and I still do not have an answer. The last thing I tried was to create a new (very simple) test to ensure that nothing in the existing tests was causing this failure. (See attached .js file.)

This new/simple test fails too.

When I ran the test with a screen-shot generator, I see that while the tests are able to find and click on the UI elements that initiate the creation of a new workitem, the resulting pages are never displayed. It seems like PhantomJS gets stuck or lost and it not able to open the open the fields/page in which a new workitem's title, description, etc. fields are displayed.

I have no idea why this is happening, but that is how/where all the tests are suddenly failing. The really odd things is that in the past, these tests were running cleanly.

The tests, of course, are all running cleanly for me when they are run locally. They only fail when they are run in docker.

I also just tried upgrading to the latest released (2.1.14) version of PhantomJS - no luck.

The test is:
```

var WorkItemListPage = require('./page-objects/work-item-list.page'),
  testSupport = require('./testSupport');

var until = protractor.ExpectedConditions;
var waitTime = 30000;

describe('Work item list', function () {
  var page, items, browserMode;

  beforeEach(function () {
    testSupport.setBrowserMode('phone');
    page = new WorkItemListPage(true);
  });

  it('Creating a new quick add work item and delete - phone.', function () {

        testSupport.setBrowserMode('phone');

        /* Click the add button */
        page.clickWorkItemQuickAdd();

        /* Enter the workitem title */
        page.typeQuickAddWorkItemTitle("titleText");

        /* The description field is not displayed on phones - If the UI element is present, enter the description */
        page.workItemQuickAddDesc.isDisplayed().then(function(visible) {
            if (visible) {
                page.typeQuickAddWorkItemDesc("titleText");
            } 
        });

        /* Click the save button */
        page.clickQuickAddSave();

        /* Return the newly created workitem */
        browser.wait(until.presenceOf(page.workItemByTitle("titleText")), waitTime, 'Failed to find workItem');
  });


 it('Create WorkItem and creatorname and image is relecting', function () {

       testSupport.setBrowserMode('desktop');
        //console.log (theText);

        /* Click the add button */
        page.clickDetailedDialogButton();

        /* Select the workitem type */
        var detailPage = page.clickDetailedIcon("userstory");

        /* Enter the workitem description */
        browser.wait(until.visibilityOf(detailPage.workItemDetailTitle), waitTime, 'Failed to find workItemList');  
        detailPage.setWorkItemDetailTitle ("titleText", false);

        /* Select the workitem type */
        browser.wait(until.visibilityOf(detailPage.workItemTitleSaveIcon), waitTime, 'Failed to find workItemList');  
        browser.wait(until.elementToBeClickable(detailPage.workItemTitleSaveIcon), waitTime, 'Failed to find workItemList');  
        detailPage.clickWorkItemTitleSaveIcon();

        /* Enter the workitem description */
        detailPage.clickWorkItemDetailDescription();
        browser.wait(until.visibilityOf(detailPage.workItemDetailDescription), waitTime, 'Failed to find workItemList');  
        detailPage.setWorkItemDetailDescription ("titleText", false);
        detailPage.clickWorkItemDescriptionSaveIcon();


        /* Close the workitem add dialog */
        detailPage.clickWorkItemDetailCloseButton();
        browser.wait(until.visibilityOf(page.workItemByTitle("titleText")), waitTime, 'Failed to find workItemList');  
    });

});

```

**Comment by ldimaggi** [comment]
See PR:  https://github.com/fabric8io/fabric8-planner/issues/857

**Comment by ldimaggi** [comment]
Naina has found a branch where the tests are able to run on Docker:

git clone git@github.com:naina-verma/fabric8-planner.git -b negavtive-tests-coverage

So - there must be a difference that we have to identify.

**Comment by ldimaggi** [comment]
https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-build-master/

The tests starting failing in this commit:
https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-build-master/42/

**Comment by ldimaggi** [comment]
The error seems to be in the differences between these files:
```

diff  --brief --recursive work-item_failing work-item_working 

Files work-item_failing/work-item.component.html and work-item_working/work-item.component.html differ
Files work-item_failing/work-item.component.scss and work-item_working/work-item.component.scss differ
Files work-item_failing/work-item.module.ts and work-item_working/work-item.module.ts differ
Files work-item_failing/work-item.service.ts and work-item_working/work-item.service.ts differ

Files work-item_failing/work-item-detail/work-item-comment/work-item-comment.component.html and work-item_working/work-item-detail/work-item-comment/work-item-comment.component.html differ
Files work-item_failing/work-item-detail/work-item-comment/work-item-comment.component.scss and work-item_working/work-item-detail/work-item-comment/work-item-comment.component.scss differ
Files work-item_failing/work-item-detail/work-item-comment/work-item-comment.component.ts and work-item_working/work-item-detail/work-item-comment/work-item-comment.component.ts differ

Files work-item_failing/work-item-detail/work-item-detail.component.html and work-item_working/work-item-detail/work-item-detail.component.html differ
Files work-item_failing/work-item-detail/work-item-detail.component.scss and work-item_working/work-item-detail/work-item-detail.component.scss differ
Files work-item_failing/work-item-detail/work-item-detail.component.ts and work-item_working/work-item-detail/work-item-detail.component.ts differ

Files work-item_failing/work-item-list/work-item-list-entry/work-item-list-entry.component.html and work-item_working/work-item-list/work-item-list-entry/work-item-list-entry.component.html differ
Files work-item_failing/work-item-list/work-item-list-entry/work-item-list-entry.component.scss and work-item_working/work-item-list/work-item-list-entry/work-item-list-entry.component.scss differ
Files work-item_failing/work-item-list/work-item-list-entry/work-item-list-entry.component.ts and work-item_working/work-item-list/work-item-list-entry/work-item-list-entry.component.ts differ

Files work-item_failing/work-item-quick-add/work-item-quick-add.component.ts and work-item_working/work-item-quick-add/work-item-quick-add.component.ts differ

```

**Comment by ldimaggi** [comment]
Build #40
https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-build-master/40/
git clone git@github.com:sanbornsen/fabric8-planner.git -b issue_710
------> Tests pass when run thru docker locally

Build #41
https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-build-master/41/
git clone git@github.com:sanbornsen/fabric8-planner.git -b issue_708
------> Tests fail when run thru docker locally

Diff files:

src/app/models/iteration.model.ts
src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.module.ts
src/app/iteration/iteration.service.ts

**Comment by ldimaggi** [comment]
Replacing the iteration.component.html file with the same file from build #40 results in the tests running with the following two (expected) errors:

```

[00:28:18] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[00:28:18] I/launcher - Running 1 instances of WebDriver
Started
...........................................F.F....................................

Failures:
1) Iteration tests ::  Verify Iteration add button and label are clickable + dialoge label is present -phone 
  Message:
    Failed: No element found using locator: By(css selector, *[id="cancel-iteration-button"])
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, *[id="cancel-iteration-button"])
        at WebDriverError (/home/almighty/node_modules/selenium-webdriver/lib/error.js:27:5)
        at NoSuchElementError (/home/almighty/node_modules/selenium-webdriver/lib/error.js:242:5)
        at /home/almighty/node_modules/protractor/built/element.js:707:27
        at ManagedPromise.invokeCallback_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/almighty/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)Error
        at ElementArrayFinder.applyAction_ (/home/almighty/node_modules/protractor/built/element.js:396:27)
        at ElementArrayFinder._this.(anonymous function) [as click] (/home/almighty/node_modules/protractor/built/element.js:99:30)
        at ElementFinder.(anonymous function) [as click] (/home/almighty/node_modules/protractor/built/element.js:730:22)
        at WorkItemListPage.clickCancelIteration (/home/almighty/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js:484:39)
        at Object.<anonymous> (/home/almighty/src/tests/work-item/work-item-list/iteration.spec.js:29:12)
        at /home/almighty/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/home/almighty/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    From: Task: Run it("Verify Iteration add button and label are clickable + dialoge label is present -phone ") in control flow
        at Object.<anonymous> (/home/almighty/node_modules/jasminewd2/index.js:79:14)
        at /home/almighty/node_modules/jasminewd2/index.js:16:5
        at ManagedPromise.invokeCallback_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/almighty/src/tests/work-item/work-item-list/iteration.spec.js:25:3)
        at Object.<anonymous> (/home/almighty/src/tests/work-item/work-item-list/iteration.spec.js:15:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)

2) Iteration tests ::  Verify Iteration Set Iteration Title description -hit Create -phone 
  Message:
    Failed: No element found using locator: By(css selector, *[id="create-iteration-button"])
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, *[id="create-iteration-button"])
        at WebDriverError (/home/almighty/node_modules/selenium-webdriver/lib/error.js:27:5)
        at NoSuchElementError (/home/almighty/node_modules/selenium-webdriver/lib/error.js:242:5)
        at /home/almighty/node_modules/protractor/built/element.js:707:27
        at ManagedPromise.invokeCallback_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /home/almighty/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)Error
        at ElementArrayFinder.applyAction_ (/home/almighty/node_modules/protractor/built/element.js:396:27)
        at ElementArrayFinder._this.(anonymous function) [as click] (/home/almighty/node_modules/protractor/built/element.js:99:30)
        at ElementFinder.(anonymous function) [as click] (/home/almighty/node_modules/protractor/built/element.js:730:22)
        at WorkItemListPage.clickCreateIteration (/home/almighty/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js:481:39)
        at Object.<anonymous> (/home/almighty/src/tests/work-item/work-item-list/iteration.spec.js:42:12)
        at /home/almighty/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/home/almighty/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    From: Task: Run it("Verify Iteration Set Iteration Title description -hit Create -phone ") in control flow
        at Object.<anonymous> (/home/almighty/node_modules/jasminewd2/index.js:79:14)
        at /home/almighty/node_modules/jasminewd2/index.js:16:5
        at ManagedPromise.invokeCallback_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/home/almighty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/almighty/src/tests/work-item/work-item-list/iteration.spec.js:38:3)
        at Object.<anonymous> (/home/almighty/src/tests/work-item/work-item-list/iteration.spec.js:15:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)




```

**Comment by naina-verma** [comment]
@ldimaggi @michaelkleinhenz ,

It looks like the issue is been detected in this file : https://www.diffchecker.com/A95BfR0U
The problematic functions are : https://github.com/fabric8io/fabric8-planner/commit/f7e77bde9993394e5551f3462d5097212062a6d6#diff-ff19bf08963e2d4f3df01f2b254f4ea4R39
Which makes call to the Spaces (which is not yet mocked ) and failed to execute further !
@sanbornsen is figuring out the solution for it

**Comment by ldimaggi** [comment]
The issue with the tests was that when iterations were introduced in the product code, there was no corresponding mocking for iterations, and request was therefore made to demo.almighty.io - this request failed as there is no internet connectivity from the tests running on Docker.
